"""
K-12 track catalogs for Gandal Space.

Seven hidden outlines (K through 12+): Mathematics, Physics, Chemistry,
Biology, Philosophy, English, and French. Lessons are generated by
Gemma via the existing Space ask path — this file is a catalog, not
hand-authored pages.

Progress is written to the existing OKF graph:
  student_profiles/<id>/session_state.md
  student_profiles/<id>/subject_<Subject>.md
"""

from __future__ import annotations

import os
import re
import sys
from typing import Any, Dict, List, Optional, Tuple

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AGENT_DIR = os.path.join(PROJECT_ROOT, "livekit_stack", "agent")
if AGENT_DIR not in sys.path:
    sys.path.insert(0, AGENT_DIR)

import student_memory  # noqa: E402

SUBJECTS = (
    "mathematics",
    "physics",
    "chemistry",
    "biology",
    "philosophy",
    "english",
    "french",
)

SUBJECT_TITLES = {
    "mathematics": "Mathematics",
    "physics": "Physics",
    "chemistry": "Chemistry",
    "biology": "Biology",
    "philosophy": "Philosophy",
    "english": "English",
    "french": "French",
}

SUBJECT_ALIASES = {
    "mathematics": ("math", "maths", "mathematics", "mathématiques", "mathematiques", "algebra", "geometry", "calculus", "trig"),
    "physics": ("physics", "physique"),
    "chemistry": ("chemistry", "chimie"),
    "biology": ("biology", "biologie"),
    "philosophy": ("philosophy", "philosophie"),
    "english": ("english", "anglais"),
    "french": ("french", "français", "francais"),
}

FROM_SCRATCH_PHRASES = (
    "from scratch", "start over", "starting over", "start from zero",
    "from zero", "beginner", "débutant", "debutant", "depuis le début",
    "from the beginning", "starting from scratch", "i am new", "i'm new",
)

RESUME_PHRASES = (
    "continue", "resume", "pick up where", "where i left", "where we left",
    "keep going", "continue the track", "continue learning", "continue this topic",
)

TRACK_INTENT_PHRASES = (
    "k-12", "k12", "track", "curriculum", "i want to learn", "teach me",
    "start with", "learn math", "learn maths", "learn physics",
    "learn chemistry", "learn biology", "learn philosophy",
    "learn english", "learn french", "apprendre",
)

BAND_HINTS = (
    ("algebra ii", "Algebra II"),
    ("algebra 2", "Algebra II"),
    ("precalculus", "Precalculus"),
    ("precalc", "Precalculus"),
    ("trigonometry", "Precalculus"),
    ("trig", "Precalculus"),
    ("calculus", "Calculus"),
    ("statistics", "Statistics"),
    ("probability", "Statistics"),
    ("geometry", "Geometry"),
    ("algebra i", "Algebra I"),
    ("algebra 1", "Algebra I"),
    ("algebra", "Algebra I"),
    ("pre-algebra", "6–8"),
    ("middle school", "6–8"),
    ("elementary", "3–5"),
    ("kindergarten", "K–2"),
    ("from zero", "K–2"),
)


def _t(tid: str, title: str, band: str, lo: int, hi: int, *aliases: str) -> Dict[str, Any]:
    return {
        "id": tid,
        "title": title,
        "band": band,
        "grade_lo": lo,
        "grade_hi": hi,
        "aliases": list(aliases),
        "walkable": True,
    }


# Comprehensive hidden Math outline: major K–12 topics, one lesson each.
MATH_TOPICS: List[Dict[str, Any]] = [
    # --- K–2 Foundations ---
    _t("math.k2.counting", "Counting to 20", "K–2", 0, 2, "count", "counting"),
    _t("math.k2.number_names", "Number names and numerals", "K–2", 0, 2, "number words"),
    _t("math.k2.compare", "Comparing numbers", "K–2", 0, 2, "greater than", "less than"),
    _t("math.k2.order", "Ordering numbers", "K–2", 0, 2, "least to greatest"),
    _t("math.k2.compose", "Composing and decomposing numbers", "K–2", 0, 1, "make 10", "number bonds"),
    _t("math.k2.add_facts", "Addition facts within 20", "K–2", 1, 2, "adding"),
    _t("math.k2.sub_facts", "Subtraction facts within 20", "K–2", 1, 2, "subtracting", "take away"),
    _t("math.k2.word_add_sub", "Add and subtract word problems", "K–2", 1, 2),
    _t("math.k2.place_value_tens", "Place value: tens and ones", "K–2", 1, 2, "tens ones"),
    _t("math.k2.skip_count", "Skip counting by 2, 5, and 10", "K–2", 1, 2),
    _t("math.k2.even_odd", "Even and odd numbers", "K–2", 2, 2),
    _t("math.k2.number_line", "The number line", "K–2", 1, 2),
    _t("math.k2.patterns", "Repeating patterns", "K–2", 0, 2),
    _t("math.k2.shapes_2d", "2D shapes", "K–2", 0, 2, "circle square triangle"),
    _t("math.k2.shapes_3d", "3D solids", "K–2", 1, 2, "cube sphere"),
    _t("math.k2.positional", "Positional words", "K–2", 0, 1, "above below beside"),
    _t("math.k2.length", "Measuring length", "K–2", 1, 2),
    _t("math.k2.compare_measure", "Comparing length, weight, and capacity", "K–2", 0, 2),
    _t("math.k2.time", "Telling time to the hour and half hour", "K–2", 1, 2, "clock"),
    _t("math.k2.calendar", "Calendar: days and months", "K–2", 0, 2),
    _t("math.k2.money", "Coins and money", "K–2", 1, 2, "penny nickel dime"),
    _t("math.k2.pictograph", "Pictographs and tally charts", "K–2", 1, 2),
    # --- Grades 3–5 ---
    _t("math.el.place_value", "Place value to thousands and beyond", "3–5", 3, 5),
    _t("math.el.rounding", "Rounding whole numbers", "3–5", 3, 4),
    _t("math.el.multi_add_sub", "Multi-digit addition and subtraction", "3–5", 3, 4),
    _t("math.el.mult_meaning", "Meaning of multiplication", "3–5", 3, 3, "times"),
    _t("math.el.times_tables", "Multiplication tables", "3–5", 3, 4),
    _t("math.el.div_meaning", "Meaning of division", "3–5", 3, 4),
    _t("math.el.long_mult", "Multi-digit multiplication", "3–5", 4, 5),
    _t("math.el.long_div", "Long division", "3–5", 4, 5),
    _t("math.el.factors", "Factors and multiples", "3–5", 4, 5),
    _t("math.el.primes", "Prime and composite numbers", "3–5", 4, 5),
    _t("math.el.properties", "Properties of operations", "3–5", 3, 5, "commutative associative distributive"),
    _t("math.el.estimation", "Estimation and mental math", "3–5", 3, 5),
    _t("math.el.frac_meaning", "What a fraction is", "3–5", 3, 4, "fraction"),
    _t("math.el.equiv_frac", "Equivalent fractions", "3–5", 3, 5),
    _t("math.el.compare_frac", "Comparing fractions", "3–5", 3, 5),
    _t("math.el.add_frac", "Adding fractions", "3–5", 4, 5),
    _t("math.el.sub_frac", "Subtracting fractions", "3–5", 4, 5),
    _t("math.el.mixed", "Mixed numbers and improper fractions", "3–5", 4, 5),
    _t("math.el.mult_frac", "Multiplying fractions", "3–5", 5, 5),
    _t("math.el.frac_as_div", "Fractions as division", "3–5", 5, 5),
    _t("math.el.decimals_pv", "Decimal place value", "3–5", 4, 5),
    _t("math.el.decimal_ops", "Adding and subtracting decimals", "3–5", 5, 5),
    _t("math.el.mult_dec", "Multiplying decimals", "3–5", 5, 5),
    _t("math.el.percent_intro", "Introduction to percent", "3–5", 5, 6, "percent"),
    _t("math.el.perimeter", "Perimeter", "3–5", 3, 4),
    _t("math.el.area", "Area of rectangles and rectilinear figures", "3–5", 3, 5),
    _t("math.el.volume", "Volume of rectangular prisms", "3–5", 5, 5),
    _t("math.el.angles", "Angles and degrees", "3–5", 4, 5),
    _t("math.el.classify_tri", "Classifying triangles", "3–5", 4, 5),
    _t("math.el.quads", "Quadrilaterals", "3–5", 3, 5),
    _t("math.el.symmetry", "Line symmetry", "3–5", 4, 4),
    _t("math.el.coord_q1", "Coordinate plane (first quadrant)", "3–5", 5, 5),
    _t("math.el.line_plots", "Line plots and data", "3–5", 3, 5),
    _t("math.el.elapsed", "Elapsed time", "3–5", 3, 4),
    _t("math.el.conversions", "Measurement conversions", "3–5", 4, 5),
    _t("math.el.multi_word", "Multi-step word problems", "3–5", 3, 5),
    # --- Grades 6–8 ---
    _t("math.ms.ratios", "Ratios", "6–8", 6, 6, "ratio"),
    _t("math.ms.unit_rate", "Unit rates", "6–8", 6, 7),
    _t("math.ms.proportions", "Proportions", "6–8", 6, 7),
    _t("math.ms.percent_apps", "Percent applications", "6–8", 6, 7, "percent of", "tax tip"),
    _t("math.ms.integers", "Integers", "6–8", 6, 7),
    _t("math.ms.rational_ops", "Operations with rational numbers", "6–8", 7, 7),
    _t("math.ms.abs_value", "Absolute value", "6–8", 6, 7),
    _t("math.ms.order_ops", "Order of operations", "6–8", 6, 7, "pemdas"),
    _t("math.ms.expressions", "Algebraic expressions", "6–8", 6, 7),
    _t("math.ms.one_step", "One-step equations", "6–8", 6, 7),
    _t("math.ms.two_step", "Two-step equations", "6–8", 7, 8),
    _t("math.ms.inequalities", "Inequalities", "6–8", 6, 8),
    _t("math.ms.linear_rel", "Linear relationships", "6–8", 7, 8),
    _t("math.ms.slope", "Slope", "6–8", 8, 8),
    _t("math.ms.graph_lines", "Graphing lines", "6–8", 8, 8),
    _t("math.ms.functions_intro", "Introduction to functions", "6–8", 8, 8),
    _t("math.ms.exponents", "Integer exponents", "6–8", 8, 8),
    _t("math.ms.sci_notation", "Scientific notation", "6–8", 8, 8),
    _t("math.ms.square_roots", "Square roots", "6–8", 8, 8),
    _t("math.ms.pythagoras", "Pythagorean theorem", "6–8", 8, 8, "hypotenuse"),
    _t("math.ms.transforms", "Transformations on the plane", "6–8", 8, 8, "translation rotation reflection"),
    _t("math.ms.congruence", "Congruence and similarity (intro)", "6–8", 8, 8),
    _t("math.ms.circles", "Circles: circumference and area", "6–8", 7, 8),
    _t("math.ms.area_comp", "Area of composite figures", "6–8", 6, 7),
    _t("math.ms.surface", "Surface area", "6–8", 6, 7),
    _t("math.ms.volume_3d", "Volume of prisms and cylinders", "6–8", 7, 8),
    _t("math.ms.angle_rel", "Angle relationships", "6–8", 7, 8, "vertical complementary"),
    _t("math.ms.scale", "Scale drawings", "6–8", 7, 7),
    _t("math.ms.stats_center", "Mean, median, mode, and range", "6–8", 6, 7),
    _t("math.ms.variability", "Statistical variability", "6–8", 6, 7),
    _t("math.ms.box_plot", "Box plots", "6–8", 6, 7),
    _t("math.ms.scatter", "Scatter plots", "6–8", 8, 8),
    _t("math.ms.two_way", "Two-way tables", "6–8", 8, 8),
    _t("math.ms.probability", "Simple probability", "6–8", 7, 8),
    _t("math.ms.compound_prob", "Compound events", "6–8", 7, 8),
    _t("math.ms.coord_all", "Four-quadrant coordinate plane", "6–8", 6, 6),
    # --- Algebra I ---
    _t("math.alg1.variables", "Variables and expressions", "Algebra I", 8, 9),
    _t("math.alg1.linear_eq", "Linear equations", "Algebra I", 8, 9),
    _t("math.alg1.ineq", "Linear inequalities", "Algebra I", 8, 9),
    _t("math.alg1.compound_ineq", "Compound inequalities", "Algebra I", 9, 9),
    _t("math.alg1.abs_eq", "Absolute value equations", "Algebra I", 9, 9),
    _t("math.alg1.systems_sub", "Systems of equations: substitution", "Algebra I", 8, 9),
    _t("math.alg1.systems_elim", "Systems of equations: elimination", "Algebra I", 8, 9),
    _t("math.alg1.systems_graph", "Graphing systems of equations", "Algebra I", 8, 9),
    _t("math.alg1.functions", "Functions and function notation", "Algebra I", 8, 9),
    _t("math.alg1.domain", "Domain and range", "Algebra I", 9, 9),
    _t("math.alg1.slope_int", "Slope-intercept form", "Algebra I", 8, 9),
    _t("math.alg1.point_slope", "Point-slope form", "Algebra I", 9, 9),
    _t("math.alg1.arith_seq", "Arithmetic sequences", "Algebra I", 9, 9),
    _t("math.alg1.poly_add", "Adding and subtracting polynomials", "Algebra I", 9, 9),
    _t("math.alg1.poly_mult", "Multiplying polynomials", "Algebra I", 9, 9),
    _t("math.alg1.factor_gcf", "Factoring with GCF", "Algebra I", 9, 9),
    _t("math.alg1.factor_tri", "Factoring trinomials", "Algebra I", 9, 9),
    _t("math.alg1.quad_factor", "Quadratic equations by factoring", "Algebra I", 9, 9),
    _t("math.alg1.quad_formula", "The quadratic formula", "Algebra I", 9, 10),
    _t("math.alg1.complete_sq", "Completing the square", "Algebra I", 9, 10),
    _t("math.alg1.parabolas", "Graphing parabolas", "Algebra I", 9, 10),
    _t("math.alg1.exp_fn", "Exponential functions", "Algebra I", 9, 10),
    _t("math.alg1.radicals", "Radicals and square-root functions", "Algebra I", 9, 10),
    _t("math.alg1.rational_intro", "Introduction to rational expressions", "Algebra I", 9, 10),
    _t("math.alg1.piecewise", "Piecewise functions (intro)", "Algebra I", 9, 10),
    _t("math.alg1.word", "Algebra word problems", "Algebra I", 8, 10),
    # --- Geometry ---
    _t("math.geo.undefined", "Points, lines, and planes", "Geometry", 8, 10),
    _t("math.geo.segments", "Segments, rays, and distance", "Geometry", 8, 10),
    _t("math.geo.angle_types", "Types of angles", "Geometry", 8, 10),
    _t("math.geo.parallel", "Parallel and perpendicular lines", "Geometry", 8, 10),
    _t("math.geo.tri_class", "Triangle classification", "Geometry", 8, 10),
    _t("math.geo.congruence", "Triangle congruence (SSS, SAS, ASA)", "Geometry", 9, 10),
    _t("math.geo.cpctc", "CPCTC and corresponding parts", "Geometry", 9, 10),
    _t("math.geo.tri_ineq", "Triangle inequality", "Geometry", 8, 10),
    _t("math.geo.similar", "Similar triangles", "Geometry", 9, 10),
    _t("math.geo.pythag_apps", "Pythagorean theorem applications", "Geometry", 8, 10),
    _t("math.geo.special_right", "Special right triangles", "Geometry", 9, 10, "30-60-90", "45-45-90"),
    _t("math.geo.trig_ratios", "Right-triangle trigonometry", "Geometry", 9, 10, "sohcahtoa", "sine cosine"),
    _t("math.geo.quads", "Properties of quadrilaterals", "Geometry", 9, 10),
    _t("math.geo.polygons", "Polygons and interior angles", "Geometry", 8, 10),
    _t("math.geo.circles", "Circles: chords, arcs, and inscribed angles", "Geometry", 9, 10),
    _t("math.geo.circle_eq", "Equation of a circle", "Geometry", 9, 10),
    _t("math.geo.area", "Area of polygons", "Geometry", 8, 10),
    _t("math.geo.vol_prism", "Volume of prisms and cylinders", "Geometry", 8, 10),
    _t("math.geo.vol_pyramid", "Volume of pyramids, cones, and spheres", "Geometry", 9, 10),
    _t("math.geo.surface", "Surface area of 3D solids", "Geometry", 8, 10),
    _t("math.geo.transforms", "Geometric transformations", "Geometry", 8, 10),
    _t("math.geo.coord_proof", "Coordinate geometry proofs", "Geometry", 9, 10),
    _t("math.geo.midpoint", "Midpoint and distance formulas", "Geometry", 8, 10),
    _t("math.geo.constructions", "Compass and straightedge constructions", "Geometry", 9, 10),
    _t("math.geo.proofs", "Two-column proofs", "Geometry", 9, 10),
    # --- Algebra II ---
    _t("math.alg2.complex", "Complex numbers", "Algebra II", 10, 11),
    _t("math.alg2.poly_fn", "Polynomial functions", "Algebra II", 10, 11),
    _t("math.alg2.remainder", "Remainder and factor theorems", "Algebra II", 10, 11),
    _t("math.alg2.rational_fn", "Rational functions", "Algebra II", 10, 11),
    _t("math.alg2.asymptotes", "Asymptotes", "Algebra II", 10, 11),
    _t("math.alg2.exp_growth", "Exponential growth and decay", "Algebra II", 10, 11),
    _t("math.alg2.logs", "Logarithms", "Algebra II", 10, 11, "logarithm"),
    _t("math.alg2.log_props", "Logarithm properties", "Algebra II", 10, 11),
    _t("math.alg2.exp_log_eq", "Solving exponential and log equations", "Algebra II", 10, 11),
    _t("math.alg2.seq_rec", "Recursive sequences", "Algebra II", 10, 11),
    _t("math.alg2.geo_seq", "Geometric sequences and series", "Algebra II", 10, 11),
    _t("math.alg2.arith_series", "Arithmetic series", "Algebra II", 10, 11),
    _t("math.alg2.conic_circle", "Conic sections: circles", "Algebra II", 10, 11),
    _t("math.alg2.conic_ellipse", "Conic sections: ellipses", "Algebra II", 10, 11),
    _t("math.alg2.conic_parabola", "Conic sections: parabolas", "Algebra II", 10, 11),
    _t("math.alg2.conic_hyperbola", "Conic sections: hyperbolas", "Algebra II", 10, 11),
    _t("math.alg2.matrices", "Matrices", "Algebra II", 10, 11, "matrix"),
    _t("math.alg2.systems3", "Systems in three variables", "Algebra II", 10, 11),
    _t("math.alg2.inverse", "Inverse functions", "Algebra II", 10, 11),
    _t("math.alg2.composition", "Function composition", "Algebra II", 10, 11),
    _t("math.alg2.radical_fn", "Radical functions", "Algebra II", 10, 11),
    _t("math.alg2.quad_ineq", "Quadratic inequalities", "Algebra II", 10, 11),
    _t("math.alg2.binomial", "Binomial theorem", "Algebra II", 10, 11),
    _t("math.alg2.piecewise", "Piecewise-defined functions", "Algebra II", 10, 11),
    # --- Precalculus & Trigonometry ---
    _t("math.pc.unit_circle", "The unit circle", "Precalculus", 10, 12),
    _t("math.pc.radians", "Radian measure", "Precalculus", 10, 12),
    _t("math.pc.sin_cos", "Sine and cosine graphs", "Precalculus", 10, 12),
    _t("math.pc.tan_graph", "Tangent graphs", "Precalculus", 10, 12),
    _t("math.pc.inv_trig", "Inverse trigonometric functions", "Precalculus", 11, 12),
    _t("math.pc.ident_pyth", "Pythagorean trig identities", "Precalculus", 10, 12),
    _t("math.pc.angle_add", "Angle-addition identities", "Precalculus", 11, 12),
    _t("math.pc.double", "Double-angle identities", "Precalculus", 11, 12),
    _t("math.pc.law_sines", "Law of sines", "Precalculus", 10, 12),
    _t("math.pc.law_cos", "Law of cosines", "Precalculus", 10, 12),
    _t("math.pc.polar", "Polar coordinates", "Precalculus", 11, 12),
    _t("math.pc.vectors", "Vectors", "Precalculus", 11, 12),
    _t("math.pc.parametric", "Parametric equations", "Precalculus", 11, 12),
    _t("math.pc.parent", "Parent functions and transformations", "Precalculus", 10, 12),
    _t("math.pc.partial", "Partial fractions (intro)", "Precalculus", 11, 12),
    _t("math.pc.limits_intro", "Limits (intro)", "Precalculus", 11, 12),
    # --- Statistics & Probability ---
    _t("math.stat.types", "Categorical vs quantitative data", "Statistics", 9, 12),
    _t("math.stat.displays", "Statistical displays", "Statistics", 9, 12),
    _t("math.stat.center_spread", "Measures of center and spread", "Statistics", 9, 12),
    _t("math.stat.normal", "The normal distribution", "Statistics", 10, 12),
    _t("math.stat.zscores", "Z-scores", "Statistics", 10, 12),
    _t("math.stat.sampling", "Sampling and bias", "Statistics", 9, 12),
    _t("math.stat.correlation", "Correlation and scatterplots", "Statistics", 9, 12),
    _t("math.stat.lsrl", "Least-squares regression (intro)", "Statistics", 10, 12),
    _t("math.stat.prob_rules", "Probability rules", "Statistics", 9, 12),
    _t("math.stat.conditional", "Conditional probability", "Statistics", 10, 12),
    _t("math.stat.independence", "Independence", "Statistics", 10, 12),
    _t("math.stat.permutations", "Permutations", "Statistics", 9, 12),
    _t("math.stat.combinations", "Combinations", "Statistics", 9, 12),
    _t("math.stat.binomial", "Binomial probability", "Statistics", 10, 12),
    _t("math.stat.expected", "Expected value", "Statistics", 10, 12),
    # --- Calculus 12+ ---
    _t("math.calc.limits", "Limits", "Calculus", 12, 13),
    _t("math.calc.continuity", "Continuity", "Calculus", 12, 13),
    _t("math.calc.derivative_def", "Definition of the derivative", "Calculus", 12, 13),
    _t("math.calc.power_rule", "Power rule", "Calculus", 12, 13),
    _t("math.calc.product", "Product and quotient rules", "Calculus", 12, 13),
    _t("math.calc.chain", "Chain rule", "Calculus", 12, 13),
    _t("math.calc.implicit", "Implicit differentiation", "Calculus", 12, 13),
    _t("math.calc.related", "Related rates", "Calculus", 12, 13),
    _t("math.calc.opt", "Optimization", "Calculus", 12, 13),
    _t("math.calc.sketch", "Curve sketching", "Calculus", 12, 13),
    _t("math.calc.antideriv", "Antiderivatives", "Calculus", 12, 13),
    _t("math.calc.def_int", "Definite integrals", "Calculus", 12, 13),
    _t("math.calc.ftc", "Fundamental Theorem of Calculus", "Calculus", 12, 13),
    _t("math.calc.area", "Area under a curve", "Calculus", 12, 13),
    _t("math.calc.usub", "u-substitution (intro)", "Calculus", 12, 13),
    _t("math.calc.volume", "Volume of revolution (intro)", "Calculus", 12, 13),
    _t("math.calc.diff_eq", "Differential equations (intro)", "Calculus", 12, 13),
]


PHYSICS_TOPICS: List[Dict[str, Any]] = [
    # --- K–2 ---
    _t("phy.k2.senses", "Our five senses", "K–2", 0, 2, "five senses"),
    _t("phy.k2.pushes", "Pushes and pulls", "K–2", 0, 2, "push and pull"),
    _t("phy.k2.fast_slow", "Fast and slow", "K–2", 0, 2),
    _t("phy.k2.heavy_light", "Heavy and light", "K–2", 0, 2),
    _t("phy.k2.float_sink", "Floating and sinking", "K–2", 0, 2),
    _t("phy.k2.magnets", "Magnets stick", "K–2", 1, 2, "magnets"),
    _t("phy.k2.shadows", "Shadows and sunlight", "K–2", 0, 2, "shadows"),
    _t("phy.k2.hot_cold", "Hot and cold", "K–2", 0, 2),
    _t("phy.k2.sounds", "Sounds we hear", "K–2", 0, 2),
    _t("phy.k2.day_night", "Day and night", "K–2", 0, 2),
    _t("phy.k2.weather", "Weather we feel", "K–2", 0, 2),
    _t("phy.k2.ramp", "Rolling down a ramp", "K–2", 1, 2),
    # --- 3–5 ---
    _t("phy.el.forces", "Forces around us", "3–5", 3, 5),
    _t("phy.el.gravity", "Gravity pulls down", "3–5", 3, 5, "gravity"),
    _t("phy.el.friction", "Friction", "3–5", 3, 5),
    _t("phy.el.machines", "Simple machines", "3–5", 3, 5, "lever pulley"),
    _t("phy.el.motion", "Motion and speed", "3–5", 3, 5),
    _t("phy.el.energy_use", "Energy we use", "3–5", 3, 5),
    _t("phy.el.light", "Light and shadows", "3–5", 3, 5),
    _t("phy.el.reflection", "Reflection of light", "3–5", 4, 5),
    _t("phy.el.sound", "How sound travels", "3–5", 3, 5),
    _t("phy.el.electric", "Electricity basics", "3–5", 4, 5),
    _t("phy.el.poles", "Magnets and poles", "3–5", 3, 5),
    _t("phy.el.states", "Solids, liquids, and gases in motion", "3–5", 3, 5),
    _t("phy.el.heat", "Heat moving from hot to cold", "3–5", 3, 5),
    _t("phy.el.solar", "The solar system", "3–5", 3, 5),
    _t("phy.el.earth_moon", "Earth, moon, and sun", "3–5", 3, 5),
    _t("phy.el.stars", "Stars and constellations", "3–5", 4, 5),
    # --- 6–8 ---
    _t("phy.ms.method", "Measuring in physics", "6–8", 6, 8),
    _t("phy.ms.speed", "Speed, velocity, and acceleration", "6–8", 6, 8, "velocity", "acceleration"),
    _t("phy.ms.dt_graph", "Distance-time graphs", "6–8", 6, 8),
    _t("phy.ms.balanced", "Balanced and unbalanced forces", "6–8", 6, 8),
    _t("phy.ms.n1", "Newton's first law", "6–8", 7, 8, "inertia"),
    _t("phy.ms.n2", "Newton's second law", "6–8", 7, 8, "f=ma"),
    _t("phy.ms.n3", "Newton's third law", "6–8", 7, 8),
    _t("phy.ms.mass_weight", "Mass versus weight", "6–8", 6, 8),
    _t("phy.ms.work", "Work and energy (intro)", "6–8", 7, 8),
    _t("phy.ms.ke_pe", "Kinetic and potential energy", "6–8", 7, 8),
    _t("phy.ms.conserve_e", "Conservation of energy (intro)", "6–8", 8, 8),
    _t("phy.ms.waves", "Waves", "6–8", 7, 8),
    _t("phy.ms.freq", "Frequency and wavelength", "6–8", 7, 8),
    _t("phy.ms.sound_ms", "Sound as a wave", "6–8", 7, 8),
    _t("phy.ms.light_wave", "Light as a wave", "6–8", 7, 8),
    _t("phy.ms.refract", "Reflection and refraction", "6–8", 7, 8),
    _t("phy.ms.color", "Color and the spectrum", "6–8", 7, 8),
    _t("phy.ms.static", "Static electricity", "6–8", 7, 8),
    _t("phy.ms.current", "Current electricity", "6–8", 7, 8),
    _t("phy.ms.circuits", "Series and parallel circuits", "6–8", 7, 8),
    _t("phy.ms.vcr", "Voltage, current, and resistance", "6–8", 8, 8),
    _t("phy.ms.magnetism", "Magnetism", "6–8", 7, 8),
    _t("phy.ms.electromag", "Electromagnets", "6–8", 8, 8),
    _t("phy.ms.density", "Density", "6–8", 6, 7),
    _t("phy.ms.pressure", "Pressure", "6–8", 7, 8),
    _t("phy.ms.buoyancy", "Buoyancy", "6–8", 7, 8),
    _t("phy.ms.temp", "Heat and temperature", "6–8", 6, 8),
    _t("phy.ms.expand", "Thermal expansion", "6–8", 7, 8),
    _t("phy.ms.seasons", "Why we have seasons", "6–8", 6, 7),
    _t("phy.ms.space_g", "Gravity in space", "6–8", 7, 8),
    # --- HS Mechanics ---
    _t("phy.mech.si", "SI units and measurement", "Mechanics", 9, 11),
    _t("phy.mech.vectors", "Vectors and scalars", "Mechanics", 9, 11),
    _t("phy.mech.kinem1d", "Kinematics in one dimension", "Mechanics", 9, 11),
    _t("phy.mech.freefall", "Free fall", "Mechanics", 9, 11),
    _t("phy.mech.projectile", "Projectile motion", "Mechanics", 9, 11),
    _t("phy.mech.newton", "Newton's laws of motion", "Mechanics", 9, 11),
    _t("phy.mech.fbd", "Free-body diagrams", "Mechanics", 9, 11),
    _t("phy.mech.friction_hs", "Static and kinetic friction", "Mechanics", 9, 11),
    _t("phy.mech.circular", "Uniform circular motion", "Mechanics", 10, 11),
    _t("phy.mech.orbits", "Gravity and orbits", "Mechanics", 10, 12),
    _t("phy.mech.momentum", "Momentum", "Mechanics", 9, 11),
    _t("phy.mech.impulse", "Impulse", "Mechanics", 9, 11),
    _t("phy.mech.collide", "Collisions", "Mechanics", 10, 11),
    _t("phy.mech.power", "Work and power", "Mechanics", 9, 11),
    _t("phy.mech.ke", "Kinetic energy", "Mechanics", 9, 11),
    _t("phy.mech.pe", "Potential energy", "Mechanics", 9, 11),
    _t("phy.mech.conserve", "Conservation of mechanical energy", "Mechanics", 10, 11),
    _t("phy.mech.com", "Center of mass", "Mechanics", 10, 12),
    _t("phy.mech.rotate", "Rotational motion (intro)", "Mechanics", 11, 12),
    _t("phy.mech.torque", "Torque", "Mechanics", 11, 12),
    _t("phy.mech.shm", "Simple harmonic motion", "Mechanics", 11, 12),
    _t("phy.mech.pendulum", "Pendulums", "Mechanics", 10, 12),
    _t("phy.mech.hooke", "Springs and Hooke's law", "Mechanics", 10, 12),
    # --- Waves / E&M ---
    _t("phy.wav.props", "Wave properties", "Waves", 10, 12),
    _t("phy.wav.interfere", "Superposition and interference", "Waves", 10, 12),
    _t("phy.wav.standing", "Standing waves", "Waves", 10, 12),
    _t("phy.wav.doppler", "The Doppler effect", "Waves", 10, 12),
    _t("phy.wav.ems", "The electromagnetic spectrum", "Waves", 10, 12),
    _t("phy.wav.mirrors", "Reflection and mirrors", "Waves", 10, 12),
    _t("phy.wav.lenses", "Refraction and lenses", "Waves", 10, 12),
    _t("phy.wav.diffraction", "Diffraction", "Waves", 11, 12),
    _t("phy.em.coulomb", "Coulomb's law", "E&M", 11, 12),
    _t("phy.em.fields", "Electric fields", "E&M", 11, 12),
    _t("phy.em.potential", "Electric potential", "E&M", 11, 12),
    _t("phy.em.cap", "Capacitance (intro)", "E&M", 11, 12),
    _t("phy.em.ohm", "Ohm's law", "E&M", 10, 12),
    _t("phy.em.kirchhoff", "Kirchhoff's rules (intro)", "E&M", 11, 12),
    _t("phy.em.bfield", "Magnetic fields", "E&M", 11, 12),
    _t("phy.em.induce", "Electromagnetic induction", "E&M", 11, 12),
    _t("phy.em.transformer", "Transformers (intro)", "E&M", 11, 12),
    _t("phy.em.acdc", "AC versus DC", "E&M", 10, 12),
    # --- Thermo / modern ---
    _t("phy.th.kinetic", "Temperature and kinetic theory", "Thermo", 10, 12),
    _t("phy.th.transfer", "Conduction, convection, and radiation", "Thermo", 10, 12),
    _t("phy.th.specific", "Specific heat", "Thermo", 10, 12),
    _t("phy.th.first", "First law of thermodynamics", "Thermo", 11, 12),
    _t("phy.th.entropy", "Second law and entropy (intro)", "Thermo", 11, 13),
    _t("phy.th.ideal", "The ideal gas law", "Thermo", 10, 12),
    _t("phy.mod.atomic", "Atomic models", "Modern", 11, 13),
    _t("phy.mod.photo", "The photoelectric effect (intro)", "Modern", 11, 13),
    _t("phy.mod.spectra", "Energy levels and spectra", "Modern", 11, 13),
    _t("phy.mod.radio", "Radioactivity", "Modern", 11, 13),
    _t("phy.mod.fission", "Nuclear fission and fusion", "Modern", 11, 13),
    _t("phy.mod.relativity", "Special relativity (intro)", "Modern", 12, 13),
    _t("phy.mod.quantum", "Quantum ideas (intro)", "Modern", 12, 13),
    _t("phy.mod.particles", "Particle physics (intro)", "Modern", 12, 13),
]


CHEMISTRY_TOPICS: List[Dict[str, Any]] = [
    # --- K–2 ---
    _t("che.k2.materials", "Materials around us", "K–2", 0, 2),
    _t("che.k2.hard_soft", "Hard and soft", "K–2", 0, 2),
    _t("che.k2.dissolve", "Mixing, sinking, and dissolving", "K–2", 0, 2, "dissolve"),
    _t("che.k2.separate", "Sorting and separating", "K–2", 0, 2),
    _t("che.k2.heat_change", "Heat can change materials", "K–2", 1, 2),
    _t("che.k2.water", "Water as a material", "K–2", 0, 2),
    _t("che.k2.safety", "Kitchen and lab safety", "K–2", 0, 2),
    _t("che.k2.recycle", "Reuse and recycle", "K–2", 0, 2),
    # --- 3–5 ---
    _t("che.el.states", "Solids, liquids, and gases", "3–5", 3, 5),
    _t("che.el.melt", "Melting and freezing", "3–5", 3, 5),
    _t("che.el.evap", "Evaporation and condensation", "3–5", 3, 5),
    _t("che.el.mixtures", "Mixtures", "3–5", 3, 5),
    _t("che.el.solutions", "Solutions", "3–5", 4, 5),
    _t("che.el.phys_chem", "Physical versus chemical change", "3–5", 4, 5),
    _t("che.el.signs", "Signs of a chemical reaction", "3–5", 4, 5),
    _t("che.el.properties", "Properties of materials", "3–5", 3, 5),
    _t("che.el.metals", "Metals and nonmetals (intro)", "3–5", 4, 5),
    _t("che.el.household", "Acids and bases around the house", "3–5", 5, 5),
    _t("che.el.air", "Air is matter", "3–5", 3, 5),
    _t("che.el.conserve", "Stuff does not vanish", "3–5", 4, 5),
    # --- 6–8 ---
    _t("che.ms.particles", "The particle model", "6–8", 6, 8),
    _t("che.ms.atoms", "Atoms", "6–8", 6, 8, "atom"),
    _t("che.ms.elements", "Elements", "6–8", 6, 8),
    _t("che.ms.ptable", "The periodic table (intro)", "6–8", 7, 8, "periodic table"),
    _t("che.ms.molecules", "Molecules", "6–8", 6, 8),
    _t("che.ms.compounds", "Compounds versus mixtures", "6–8", 6, 8),
    _t("che.ms.formulas", "Chemical formulas", "6–8", 7, 8),
    _t("che.ms.reactions", "Chemical reactions", "6–8", 7, 8),
    _t("che.ms.mass", "Conservation of mass", "6–8", 7, 8),
    _t("che.ms.acids", "Acids, bases, and pH", "6–8", 7, 8, "ph"),
    _t("che.ms.neutral", "Neutralization", "6–8", 8, 8),
    _t("che.ms.reactivity", "Metals and reactivity", "6–8", 7, 8),
    _t("che.ms.corrosion", "Corrosion and rust", "6–8", 7, 8),
    _t("che.ms.density", "Density of substances", "6–8", 6, 8),
    _t("che.ms.pure", "Pure substances", "6–8", 6, 7),
    _t("che.ms.chromato", "Chromatography", "6–8", 7, 8),
    _t("che.ms.combustion", "Combustion", "6–8", 7, 8),
    _t("che.ms.sugar_o2", "Sugar, oxygen, and carbon dioxide", "6–8", 7, 8),
    _t("che.ms.polymers", "Polymers (intro)", "6–8", 8, 8),
    _t("che.ms.solvent", "Water as a solvent", "6–8", 6, 8),
    # --- HS ---
    _t("che.hs.measure", "Measurement in chemistry", "HS Chem", 9, 11),
    _t("che.hs.structure", "Atomic structure", "HS Chem", 9, 11),
    _t("che.hs.particles", "Protons, neutrons, and electrons", "HS Chem", 9, 11),
    _t("che.hs.isotopes", "Isotopes", "HS Chem", 9, 11),
    _t("che.hs.config", "Electron configuration (intro)", "HS Chem", 10, 11),
    _t("che.hs.trends", "Periodic trends", "HS Chem", 10, 11),
    _t("che.hs.ionic", "Ionic bonding", "HS Chem", 9, 11),
    _t("che.hs.covalent", "Covalent bonding", "HS Chem", 9, 11),
    _t("che.hs.metallic", "Metallic bonding", "HS Chem", 9, 11),
    _t("che.hs.lewis", "Lewis structures", "HS Chem", 10, 11),
    _t("che.hs.vsepr", "VSEPR and molecular shape", "HS Chem", 10, 12),
    _t("che.hs.polarity", "Polarity", "HS Chem", 10, 11),
    _t("che.hs.imf", "Intermolecular forces", "HS Chem", 10, 12),
    _t("che.hs.name_ionic", "Naming ionic compounds", "HS Chem", 9, 11),
    _t("che.hs.name_cov", "Naming covalent compounds", "HS Chem", 9, 11),
    _t("che.hs.mole", "The mole", "HS Chem", 9, 11),
    _t("che.hs.molar_mass", "Molar mass", "HS Chem", 9, 11),
    _t("che.hs.stoich", "Stoichiometry", "HS Chem", 10, 11),
    _t("che.hs.limiting", "Limiting reactants", "HS Chem", 10, 12),
    _t("che.hs.yield", "Percent yield", "HS Chem", 10, 12),
    _t("che.hs.types", "Types of chemical reactions", "HS Chem", 9, 11),
    _t("che.hs.balance", "Balancing equations", "HS Chem", 9, 11),
    _t("che.hs.precip", "Precipitation reactions", "HS Chem", 10, 12),
    _t("che.hs.redox", "Redox (intro)", "HS Chem", 10, 12),
    _t("che.hs.oxnum", "Oxidation numbers", "HS Chem", 10, 12),
    _t("che.hs.acids", "Acids and bases", "HS Chem", 10, 12),
    _t("che.hs.phcalc", "pH calculations (intro)", "HS Chem", 11, 12),
    _t("che.hs.titration", "Titrations", "HS Chem", 11, 12),
    _t("che.hs.gaslaws", "Gas laws", "HS Chem", 10, 12),
    _t("che.hs.ideal", "The ideal gas law", "HS Chem", 10, 12),
    _t("che.hs.solutions", "Solutions and concentration", "HS Chem", 10, 12),
    _t("che.hs.molarity", "Molarity", "HS Chem", 10, 12),
    _t("che.hs.dilution", "Dilution", "HS Chem", 10, 12),
    _t("che.hs.solubility", "Solubility", "HS Chem", 10, 12),
    _t("che.hs.thermo", "Thermochemistry", "HS Chem", 11, 12),
    _t("che.hs.enthalpy", "Enthalpy", "HS Chem", 11, 12),
    _t("che.hs.endo", "Endothermic and exothermic", "HS Chem", 9, 12),
    _t("che.hs.rates", "Reaction rates", "HS Chem", 11, 12),
    _t("che.hs.collision", "Collision theory", "HS Chem", 11, 12),
    _t("che.hs.catalyst", "Catalysts", "HS Chem", 10, 12),
    _t("che.hs.equil", "Chemical equilibrium", "HS Chem", 11, 12),
    _t("che.hs.lechat", "Le Chatelier's principle", "HS Chem", 11, 12),
    _t("che.hs.org", "Organic chemistry (intro)", "HS Chem", 11, 13),
    _t("che.hs.hydro", "Hydrocarbons", "HS Chem", 11, 13),
    _t("che.hs.func", "Functional groups", "HS Chem", 11, 13),
    _t("che.hs.poly", "Synthetic polymers", "HS Chem", 11, 13),
    _t("che.hs.nuclear", "Nuclear chemistry", "HS Chem", 11, 13),
    _t("che.hs.electro", "Electrochemistry (intro)", "HS Chem", 12, 13),
    _t("che.hs.lab", "Lab equipment and safety", "HS Chem", 9, 12),
]


BIOLOGY_TOPICS: List[Dict[str, Any]] = [
    # --- K–2 ---
    _t("bio.k2.living", "Living and nonliving", "K–2", 0, 2),
    _t("bio.k2.animals_plants", "Animals and plants", "K–2", 0, 2),
    _t("bio.k2.body", "Our body parts", "K–2", 0, 2),
    _t("bio.k2.senses", "Senses help living things", "K–2", 0, 2),
    _t("bio.k2.eat", "What animals eat", "K–2", 0, 2),
    _t("bio.k2.babies", "Baby animals", "K–2", 0, 2),
    _t("bio.k2.grow", "How plants grow", "K–2", 0, 2),
    _t("bio.k2.habitats", "Habitats", "K–2", 0, 2),
    _t("bio.k2.weather_life", "Weather and living things", "K–2", 1, 2),
    # --- 3–5 ---
    _t("bio.el.cycles", "Life cycles", "3–5", 3, 5),
    _t("bio.el.foodchain", "Food chains", "3–5", 3, 5),
    _t("bio.el.foodweb", "Food webs", "3–5", 4, 5),
    _t("bio.el.eco", "Ecosystems (intro)", "3–5", 4, 5),
    _t("bio.el.plant_parts", "Plant parts", "3–5", 3, 5),
    _t("bio.el.seeds", "Seeds and germination", "3–5", 3, 5),
    _t("bio.el.adapt", "Animal adaptations", "3–5", 3, 5),
    _t("bio.el.traits", "Inherited traits", "3–5", 4, 5),
    _t("bio.el.fossils", "Fossils", "3–5", 3, 5),
    _t("bio.el.human", "The human body", "3–5", 3, 5),
    _t("bio.el.bones", "Bones and muscles", "3–5", 3, 5),
    _t("bio.el.heart", "Heart and lungs", "3–5", 4, 5),
    _t("bio.el.digest", "Digestion", "3–5", 4, 5),
    _t("bio.el.health", "Healthy habits", "3–5", 3, 5),
    _t("bio.el.scope", "Looking through a microscope", "3–5", 5, 5),
    # --- 6–8 ---
    _t("bio.ms.cells", "Cells", "6–8", 6, 8, "cell"),
    _t("bio.ms.cell_types", "Plant versus animal cells", "6–8", 6, 8),
    _t("bio.ms.org", "Cell organelles", "6–8", 6, 8),
    _t("bio.ms.uni", "Unicellular and multicellular life", "6–8", 6, 8),
    _t("bio.ms.class", "Classifying living things", "6–8", 6, 8),
    _t("bio.ms.bacteria", "Bacteria", "6–8", 6, 8),
    _t("bio.ms.fungi", "Fungi", "6–8", 6, 8),
    _t("bio.ms.protists", "Protists", "6–8", 7, 8),
    _t("bio.ms.photo", "Photosynthesis", "6–8", 6, 8, "photosynthesis"),
    _t("bio.ms.resp", "Cellular respiration (intro)", "6–8", 7, 8),
    _t("bio.ms.osmosis", "Diffusion and osmosis", "6–8", 7, 8),
    _t("bio.ms.mitosis_i", "Mitosis (intro)", "6–8", 8, 8),
    _t("bio.ms.repro", "Reproduction", "6–8", 7, 8),
    _t("bio.ms.genetics_i", "Genetics (intro)", "6–8", 8, 8),
    _t("bio.ms.dna_i", "DNA (intro)", "6–8", 8, 8),
    _t("bio.ms.select", "Natural selection (intro)", "6–8", 8, 8),
    _t("bio.ms.evo_ev", "Evidence for change over time", "6–8", 8, 8),
    _t("bio.ms.ecology", "Ecology", "6–8", 6, 8),
    _t("bio.ms.pop", "Populations", "6–8", 7, 8),
    _t("bio.ms.biomes", "Biomes", "6–8", 6, 8),
    _t("bio.ms.impact", "Humans and the environment", "6–8", 6, 8),
    _t("bio.ms.systems", "Body systems overview", "6–8", 7, 8),
    _t("bio.ms.nervous_i", "The nervous system (intro)", "6–8", 8, 8),
    _t("bio.ms.immune_i", "The immune system (intro)", "6–8", 8, 8),
    # --- HS ---
    _t("bio.hs.biochem", "Chemistry of life", "HS Bio", 9, 11),
    _t("bio.hs.water", "Water and living things", "HS Bio", 9, 11),
    _t("bio.hs.macro", "Macromolecules", "HS Bio", 9, 11),
    _t("bio.hs.enzymes", "Enzymes", "HS Bio", 9, 11),
    _t("bio.hs.membrane", "The cell membrane", "HS Bio", 9, 11),
    _t("bio.hs.transport", "Passive and active transport", "HS Bio", 9, 11),
    _t("bio.hs.light", "Light reactions of photosynthesis", "HS Bio", 9, 11),
    _t("bio.hs.resp", "Cellular respiration", "HS Bio", 9, 11),
    _t("bio.hs.krebs", "Glycolysis and the Krebs cycle", "HS Bio", 10, 12),
    _t("bio.hs.cycle", "The cell cycle", "HS Bio", 9, 11),
    _t("bio.hs.mitosis", "Mitosis", "HS Bio", 9, 11),
    _t("bio.hs.meiosis", "Meiosis", "HS Bio", 9, 11),
    _t("bio.hs.mendel", "Mendelian genetics", "HS Bio", 9, 11),
    _t("bio.hs.punnett", "Punnett squares", "HS Bio", 9, 11),
    _t("bio.hs.incomplete", "Incomplete dominance", "HS Bio", 10, 12),
    _t("bio.hs.dna", "DNA structure", "HS Bio", 9, 11),
    _t("bio.hs.replicate", "DNA replication", "HS Bio", 10, 12),
    _t("bio.hs.transcribe", "Transcription", "HS Bio", 10, 12),
    _t("bio.hs.translate", "Translation", "HS Bio", 10, 12),
    _t("bio.hs.mutate", "Mutations", "HS Bio", 10, 12),
    _t("bio.hs.biotech", "Biotechnology (intro)", "HS Bio", 11, 13),
    _t("bio.hs.evolution", "Evolution", "HS Bio", 9, 12),
    _t("bio.hs.evidence", "Evidence for evolution", "HS Bio", 9, 12),
    _t("bio.hs.speciation", "Speciation", "HS Bio", 11, 12),
    _t("bio.hs.phylo", "Phylogeny", "HS Bio", 11, 12),
    _t("bio.hs.virus", "Bacteria and viruses", "HS Bio", 9, 12),
    _t("bio.hs.immune", "Immune response", "HS Bio", 10, 12),
    _t("bio.hs.nervous", "The nervous system", "HS Bio", 10, 12),
    _t("bio.hs.endo", "The endocrine system", "HS Bio", 10, 12),
    _t("bio.hs.cardio", "The circulatory system", "HS Bio", 9, 12),
    _t("bio.hs.lungs", "The respiratory system", "HS Bio", 9, 12),
    _t("bio.hs.digest", "The digestive system", "HS Bio", 9, 12),
    _t("bio.hs.excrete", "The excretory system", "HS Bio", 10, 12),
    _t("bio.hs.muscle", "The musculoskeletal system", "HS Bio", 9, 12),
    _t("bio.hs.dev", "Reproduction and development", "HS Bio", 10, 12),
    _t("bio.hs.homeo", "Homeostasis", "HS Bio", 10, 12),
    _t("bio.hs.plant_st", "Plant structure", "HS Bio", 9, 12),
    _t("bio.hs.plant_tr", "Plant transport", "HS Bio", 10, 12),
    _t("bio.hs.hormones", "Plant hormones", "HS Bio", 11, 12),
    _t("bio.hs.pop_eco", "Population ecology", "HS Bio", 10, 12),
    _t("bio.hs.comm", "Community ecology", "HS Bio", 10, 12),
    _t("bio.hs.energy", "Ecosystem energy flow", "HS Bio", 9, 12),
    _t("bio.hs.carbon", "The carbon cycle", "HS Bio", 9, 12),
    _t("bio.hs.nitrogen", "The nitrogen cycle", "HS Bio", 10, 12),
    _t("bio.hs.biodiversity", "Biodiversity", "HS Bio", 9, 12),
    _t("bio.hs.conserve", "Conservation biology", "HS Bio", 11, 13),
]


PHILOSOPHY_TOPICS: List[Dict[str, Any]] = [
    # --- K–2: wonder, fairness, feelings ---
    _t("phi.k2.why", "Asking why", "K–2", 0, 2, "wondering why"),
    _t("phi.k2.wonder", "Wondering about the world", "K–2", 0, 2),
    _t("phi.k2.fair", "What is fair?", "K–2", 0, 2, "fairness"),
    _t("phi.k2.share", "Sharing and taking turns", "K–2", 0, 2),
    _t("phi.k2.kind", "Kindness", "K–2", 0, 2),
    _t("phi.k2.true", "True stories and make-believe", "K–2", 0, 2),
    _t("phi.k2.feelings", "Feelings and choices", "K–2", 0, 2),
    _t("phi.k2.friend", "Being a good friend", "K–2", 0, 2),
    _t("phi.k2.rules", "Rules we follow", "K–2", 0, 2),
    _t("phi.k2.who", "Who am I?", "K–2", 1, 2),
    # --- 3–5 ---
    _t("phi.el.reason", "What is a good reason?", "3–5", 3, 5),
    _t("phi.el.justice", "Fairness and justice", "3–5", 3, 5),
    _t("phi.el.rights", "Rights and responsibilities", "3–5", 4, 5),
    _t("phi.el.honesty", "Honesty", "3–5", 3, 5),
    _t("phi.el.courage", "Courage", "3–5", 3, 5),
    _t("phi.el.friendship", "What makes a friendship?", "3–5", 3, 5),
    _t("phi.el.real", "What is real?", "3–5", 4, 5),
    _t("phi.el.dreams", "Dreams and waking life", "3–5", 4, 5),
    _t("phi.el.views", "Different points of view", "3–5", 3, 5),
    _t("phi.el.disagree", "Respecting disagreement", "3–5", 4, 5),
    _t("phi.el.community", "Living in a community", "3–5", 3, 5),
    _t("phi.el.why_rules", "Why communities have rules", "3–5", 4, 5),
    _t("phi.el.beauty", "Beauty around us", "3–5", 3, 5),
    # --- 6–8 ---
    _t("phi.ms.what", "What is philosophy?", "6–8", 6, 8),
    _t("phi.ms.questions", "Asking better questions", "6–8", 6, 8),
    _t("phi.ms.args", "Arguments and reasons", "6–8", 6, 8),
    _t("phi.ms.fact", "Fact versus opinion", "6–8", 6, 8),
    _t("phi.ms.thought", "Thought experiments", "6–8", 7, 8),
    _t("phi.ms.identity", "Who am I becoming?", "6–8", 6, 8),
    _t("phi.ms.freewill", "Free will (intro)", "6–8", 8, 8),
    _t("phi.ms.rightwrong", "Right and wrong", "6–8", 6, 8, "ethics"),
    _t("phi.ms.conseq", "Consequences of actions", "6–8", 6, 8),
    _t("phi.ms.golden", "The golden rule", "6–8", 6, 8),
    _t("phi.ms.virtue", "Virtue (intro)", "6–8", 7, 8),
    _t("phi.ms.happy", "What is happiness?", "6–8", 6, 8),
    _t("phi.ms.know", "Knowledge versus belief", "6–8", 7, 8),
    _t("phi.ms.howknow", "How do we know?", "6–8", 7, 8),
    _t("phi.ms.appear", "Appearance versus reality", "6–8", 8, 8),
    _t("phi.ms.mind", "Mind and body (intro)", "6–8", 8, 8),
    _t("phi.ms.freedom", "Freedom and rules", "6–8", 7, 8),
    _t("phi.ms.justice_c", "Justice in a community", "6–8", 7, 8),
    _t("phi.ms.citizen", "What is a good citizen?", "6–8", 7, 8),
    _t("phi.ms.art", "Art and beauty", "6–8", 6, 8),
    # --- HS 9–12+ ---
    _t("phi.hs.logic", "Logic and valid arguments", "HS Phil", 9, 12),
    _t("phi.hs.fallacy", "Informal fallacies", "HS Phil", 9, 12),
    _t("phi.hs.deduce", "Deduction and induction", "HS Phil", 9, 12),
    _t("phi.hs.socrates", "Socrates and the examined life", "HS Phil", 9, 12),
    _t("phi.hs.cave", "Plato's cave", "HS Phil", 9, 12),
    _t("phi.hs.aristotle", "Aristotle on virtue", "HS Phil", 9, 12),
    _t("phi.hs.util", "Utilitarianism (intro)", "HS Phil", 10, 12),
    _t("phi.hs.duty", "Duty and rights", "HS Phil", 10, 12),
    _t("phi.hs.virtue", "Virtue ethics", "HS Phil", 10, 12),
    _t("phi.hs.lying", "Honesty, lying, and trust", "HS Phil", 9, 12),
    _t("phi.hs.fair_app", "Applied fairness", "HS Phil", 9, 12),
    _t("phi.hs.bioeth", "Bioethics (intro)", "HS Phil", 11, 13),
    _t("phi.hs.episteme", "What is knowledge?", "HS Phil", 10, 12, "epistemology"),
    _t("phi.hs.skeptic", "Skepticism", "HS Phil", 11, 12),
    _t("phi.hs.empiric", "Experience and reason", "HS Phil", 11, 12),
    _t("phi.hs.mind_hs", "Philosophy of mind", "HS Phil", 11, 13),
    _t("phi.hs.person", "Personal identity", "HS Phil", 10, 12),
    _t("phi.hs.determinism", "Free will and determinism", "HS Phil", 11, 13),
    _t("phi.hs.liberty", "Liberty", "HS Phil", 10, 12),
    _t("phi.hs.contract", "The social contract (intro)", "HS Phil", 10, 12),
    _t("phi.hs.equality", "Justice and equality", "HS Phil", 10, 12),
    _t("phi.hs.rights_h", "Human rights", "HS Phil", 9, 12),
    _t("phi.hs.science", "Philosophy of science (intro)", "HS Phil", 11, 13),
    _t("phi.hs.religion", "Questions about religion (respectful intro)", "HS Phil", 11, 13),
    _t("phi.hs.aesthetics", "Aesthetics", "HS Phil", 10, 12),
    _t("phi.hs.exist", "Existential questions", "HS Phil", 11, 13),
    _t("phi.hs.meaning", "Meaning and purpose", "HS Phil", 10, 13),
    _t("phi.hs.language", "Language and meaning", "HS Phil", 11, 13),
    _t("phi.hs.feminist", "Feminist philosophy (intro)", "HS Phil", 11, 13),
    _t("phi.hs.env", "Environmental ethics", "HS Phil", 10, 13),
    _t("phi.hs.tech", "Technology and ethics", "HS Phil", 11, 13),
    _t("phi.hs.personhood", "What is a person?", "HS Phil", 11, 13),
]


ENGLISH_TOPICS: List[Dict[str, Any]] = [
    # --- K–2: alphabets → early reading / speaking / writing ---
    _t("eng.k2.alphabet", "The English alphabet", "K–2", 0, 2, "english alphabet", "abc"),
    _t("eng.k2.letter_names", "Letter names", "K–2", 0, 2),
    _t("eng.k2.letter_sounds", "Letter sounds", "K–2", 0, 2, "phonics"),
    _t("eng.k2.vowels", "Vowels", "K–2", 0, 2),
    _t("eng.k2.consonants", "Consonants", "K–2", 0, 2),
    _t("eng.k2.case", "Capital and lowercase letters", "K–2", 0, 2),
    _t("eng.k2.ae", "Letters A through E", "K–2", 0, 1),
    _t("eng.k2.fj", "Letters F through J", "K–2", 0, 1),
    _t("eng.k2.ko", "Letters K through O", "K–2", 0, 1),
    _t("eng.k2.pt", "Letters P through T", "K–2", 0, 1),
    _t("eng.k2.uz", "Letters U through Z", "K–2", 0, 1),
    _t("eng.k2.begin", "Beginning sounds", "K–2", 0, 2),
    _t("eng.k2.end", "Ending sounds", "K–2", 1, 2),
    _t("eng.k2.rhyme", "Rhyming", "K–2", 0, 2),
    _t("eng.k2.syllables", "Syllables", "K–2", 1, 2),
    _t("eng.k2.sight", "Sight words", "K–2", 1, 2),
    _t("eng.k2.cvc", "CVC words", "K–2", 1, 2),
    _t("eng.k2.families", "Word families", "K–2", 1, 2),
    _t("eng.k2.sentences", "Simple sentences", "K–2", 1, 2),
    _t("eng.k2.questions", "Asking questions", "K–2", 1, 2),
    _t("eng.k2.listen", "Listening", "K–2", 0, 2),
    _t("eng.k2.speak", "Speaking in complete sentences", "K–2", 1, 2),
    _t("eng.k2.form", "Forming letters", "K–2", 0, 2),
    _t("eng.k2.name", "Writing your name", "K–2", 0, 2),
    _t("eng.k2.picture", "Reading a picture book", "K–2", 0, 2),
    # --- 3–5: reading / grammar ---
    _t("eng.el.phonics", "Phonics review", "3–5", 3, 4),
    _t("eng.el.vowel_len", "Long and short vowels", "3–5", 3, 4),
    _t("eng.el.blends", "Blends and digraphs", "3–5", 3, 4),
    _t("eng.el.prefix", "Prefixes", "3–5", 4, 5),
    _t("eng.el.suffix", "Suffixes", "3–5", 4, 5),
    _t("eng.el.nouns", "Nouns", "3–5", 3, 5),
    _t("eng.el.verbs", "Verbs", "3–5", 3, 5),
    _t("eng.el.adj", "Adjectives", "3–5", 3, 5),
    _t("eng.el.adv", "Adverbs", "3–5", 4, 5),
    _t("eng.el.pronoun", "Pronouns", "3–5", 3, 5),
    _t("eng.el.subject", "Subject and predicate", "3–5", 3, 5),
    _t("eng.el.sent_types", "Types of sentences", "3–5", 3, 5),
    _t("eng.el.caps", "Capitalization", "3–5", 3, 5),
    _t("eng.el.punct", "Punctuation", "3–5", 3, 5),
    _t("eng.el.commas", "Commas", "3–5", 4, 5),
    _t("eng.el.spelling", "Spelling patterns", "3–5", 3, 5),
    _t("eng.el.synonym", "Synonyms and antonyms", "3–5", 3, 5),
    _t("eng.el.context", "Context clues", "3–5", 4, 5),
    _t("eng.el.main", "Main idea", "3–5", 3, 5),
    _t("eng.el.sequence", "Sequencing", "3–5", 3, 5),
    _t("eng.el.character", "Characters and setting", "3–5", 3, 5),
    _t("eng.el.fable", "Folktales and fables", "3–5", 3, 5),
    _t("eng.el.poetry", "Poetry (intro)", "3–5", 3, 5),
    _t("eng.el.paragraph", "Writing a paragraph", "3–5", 4, 5),
    _t("eng.el.narrative", "Narrative writing", "3–5", 4, 5),
    _t("eng.el.info", "Informative writing", "3–5", 4, 5),
    _t("eng.el.opinion", "Opinion writing", "3–5", 4, 5),
    _t("eng.el.speak_group", "Speaking to a group", "3–5", 3, 5),
    _t("eng.el.listen_d", "Listening for details", "3–5", 3, 5),
    # --- 6–8: grammar / conjugation / reading ---
    _t("eng.ms.pos", "Parts of speech review", "6–8", 6, 8),
    _t("eng.ms.tenses", "Verb tenses", "6–8", 6, 8, "conjugation"),
    _t("eng.ms.sva", "Subject-verb agreement", "6–8", 6, 8),
    _t("eng.ms.irregular", "Regular and irregular verbs", "6–8", 6, 8),
    _t("eng.ms.conj", "Conjugating common English verbs", "6–8", 6, 8),
    _t("eng.ms.pro_agr", "Pronoun agreement", "6–8", 6, 8),
    _t("eng.ms.adj_adv", "Adjective versus adverb", "6–8", 6, 8),
    _t("eng.ms.prep", "Prepositions", "6–8", 6, 8),
    _t("eng.ms.conjw", "Conjunctions", "6–8", 6, 8),
    _t("eng.ms.clauses", "Clauses", "6–8", 7, 8),
    _t("eng.ms.sent_struct", "Simple, compound, and complex sentences", "6–8", 7, 8),
    _t("eng.ms.dialogue", "Punctuating dialogue", "6–8", 6, 8),
    _t("eng.ms.roots", "Vocabulary from roots", "6–8", 6, 8),
    _t("eng.ms.fig", "Figurative language", "6–8", 6, 8),
    _t("eng.ms.theme", "Theme", "6–8", 6, 8),
    _t("eng.ms.plot", "Plot", "6–8", 6, 8),
    _t("eng.ms.pov", "Point of view", "6–8", 6, 8),
    _t("eng.ms.infer", "Inference", "6–8", 6, 8),
    _t("eng.ms.summary", "Summarizing", "6–8", 6, 8),
    _t("eng.ms.compare", "Compare and contrast", "6–8", 6, 8),
    _t("eng.ms.argument", "Argument paragraphs", "6–8", 7, 8),
    _t("eng.ms.essay", "Essay structure", "6–8", 7, 8),
    _t("eng.ms.research", "Research (intro)", "6–8", 8, 8),
    _t("eng.ms.revise", "Revising and editing", "6–8", 6, 8),
    _t("eng.ms.oral", "Oral presentation", "6–8", 6, 8),
    _t("eng.ms.debate", "Discussion and debate (intro)", "6–8", 7, 8),
    # --- HS: writing / speaking / rhetoric ---
    _t("eng.hs.grammar", "Advanced grammar", "HS Eng", 9, 12),
    _t("eng.hs.mood", "Verb mood and voice", "HS Eng", 9, 12),
    _t("eng.hs.cond", "Conditional sentences", "HS Eng", 9, 12),
    _t("eng.hs.parallel", "Parallel structure", "HS Eng", 9, 12),
    _t("eng.hs.modifier", "Modifier placement", "HS Eng", 10, 12),
    _t("eng.hs.rhetoric", "Ethos, pathos, and logos", "HS Eng", 9, 12),
    _t("eng.hs.devices", "Literary devices", "HS Eng", 9, 12),
    _t("eng.hs.poetry", "Poetry analysis", "HS Eng", 9, 12),
    _t("eng.hs.drama", "Drama and Shakespeare (intro)", "HS Eng", 9, 12),
    _t("eng.hs.novel", "Novel study skills", "HS Eng", 9, 12),
    _t("eng.hs.info", "Reading informational texts", "HS Eng", 9, 12),
    _t("eng.hs.arg_essay", "Argumentative essays", "HS Eng", 9, 12),
    _t("eng.hs.research", "Research papers", "HS Eng", 10, 12),
    _t("eng.hs.cite", "Citation and sources", "HS Eng", 10, 12),
    _t("eng.hs.style", "Style and tone", "HS Eng", 9, 12),
    _t("eng.hs.craft", "Narrative craft", "HS Eng", 9, 12),
    _t("eng.hs.speech", "Speech writing", "HS Eng", 9, 12),
    _t("eng.hs.persuade", "Persuasive speaking", "HS Eng", 9, 12),
    _t("eng.hs.interview", "Interview skills", "HS Eng", 10, 12),
    _t("eng.hs.career", "College and career writing", "HS Eng", 11, 13),
    _t("eng.hs.media", "Media literacy", "HS Eng", 9, 12),
    _t("eng.hs.connote", "Connotation and denotation", "HS Eng", 9, 12),
    _t("eng.hs.satire", "Satire (intro)", "HS Eng", 11, 13),
    _t("eng.hs.synth", "Synthesis writing", "HS Eng", 11, 13),
]


FRENCH_TOPICS: List[Dict[str, Any]] = [
    # --- K–2: alphabet → sounds → first words ---
    _t("fre.k2.alphabet", "L'alphabet français", "K–2", 0, 2, "alphabet français", "french alphabet"),
    _t("fre.k2.names", "French letter names", "K–2", 0, 2),
    _t("fre.k2.acc_e", "Accents: é è ê ë", "K–2", 0, 2, "accent aigu"),
    _t("fre.k2.acc_a", "Accents: à â ç", "K–2", 0, 2, "cédille", "cedille"),
    _t("fre.k2.acc_u", "Accents: ù û ï î ô", "K–2", 1, 2),
    _t("fre.k2.bonjour", "Greetings: bonjour and salut", "K–2", 0, 2, "bonjour"),
    _t("fre.k2.name", "Saying your name", "K–2", 0, 2, "je m'appelle"),
    _t("fre.k2.please", "S'il te plaît and merci", "K–2", 0, 2, "merci"),
    _t("fre.k2.num10", "Numbers 1 to 10", "K–2", 0, 2),
    _t("fre.k2.num20", "Numbers 11 to 20", "K–2", 1, 2),
    _t("fre.k2.colors", "Colors", "K–2", 0, 2, "couleurs"),
    _t("fre.k2.family", "Family words", "K–2", 0, 2, "famille"),
    _t("fre.k2.class", "Classroom objects", "K–2", 1, 2),
    _t("fre.k2.days", "Days of the week", "K–2", 1, 2, "lundi"),
    _t("fre.k2.months", "Months", "K–2", 1, 2),
    _t("fre.k2.weather", "Weather phrases", "K–2", 1, 2, "il pleut"),
    _t("fre.k2.intro", "Simple introductions", "K–2", 1, 2),
    _t("fre.k2.listen", "Listening to French sounds", "K–2", 0, 2),
    _t("fre.k2.repeat", "Repeating phrases", "K–2", 0, 2),
    _t("fre.k2.write", "Writing French letters", "K–2", 0, 2),
    # --- 3–5 ---
    _t("fre.el.articles", "Articles: le, la, les, un, une", "3–5", 3, 5),
    _t("fre.el.gender", "Gender of nouns", "3–5", 3, 5),
    _t("fre.el.plural", "Plural nouns", "3–5", 3, 5),
    _t("fre.el.adj", "Adjectives (intro)", "3–5", 4, 5),
    _t("fre.el.avoir", "Avoir", "3–5", 3, 5, "avoir"),
    _t("fre.el.etre", "Être", "3–5", 3, 5, "etre", "être"),
    _t("fre.el.je_tu", "Je, tu, il, elle", "3–5", 3, 5),
    _t("fre.el.nous", "Nous, vous, ils, elles", "3–5", 3, 5),
    _t("fre.el.er_intro", "Regular -er verbs (intro)", "3–5", 4, 5),
    _t("fre.el.aimer", "Likes and dislikes: aimer", "3–5", 3, 5, "aimer"),
    _t("fre.el.food", "Food vocabulary", "3–5", 3, 5),
    _t("fre.el.animals", "Animals", "3–5", 3, 5),
    _t("fre.el.body", "Body parts", "3–5", 3, 5),
    _t("fre.el.house", "House and home", "3–5", 4, 5),
    _t("fre.el.time", "Telling time (intro)", "3–5", 4, 5),
    _t("fre.el.estce", "Asking questions with est-ce que", "3–5", 4, 5),
    _t("fre.el.nepas", "Negation: ne…pas", "3–5", 4, 5),
    _t("fre.el.read", "Simple reading", "3–5", 3, 5),
    _t("fre.el.copy", "Copying sentences", "3–5", 3, 5),
    _t("fre.el.me", "Speaking about yourself", "3–5", 3, 5),
    # --- 6–8: conjugation ---
    _t("fre.ms.er", "Regular -er conjugation", "6–8", 6, 8),
    _t("fre.ms.ir", "Regular -ir conjugation", "6–8", 6, 8),
    _t("fre.ms.re", "Regular -re conjugation", "6–8", 6, 8),
    _t("fre.ms.aller", "Aller", "6–8", 6, 8, "aller"),
    _t("fre.ms.faire", "Faire", "6–8", 6, 8, "faire"),
    _t("fre.ms.venir", "Venir", "6–8", 6, 8, "venir"),
    _t("fre.ms.modals", "Pouvoir, vouloir, devoir", "6–8", 7, 8),
    _t("fre.ms.refl", "Reflexive verbs (intro)", "6–8", 8, 8),
    _t("fre.ms.adj_agr", "Adjective agreement", "6–8", 6, 8),
    _t("fre.ms.poss", "Possessive adjectives", "6–8", 6, 8),
    _t("fre.ms.dem", "Demonstratives", "6–8", 7, 8),
    _t("fre.ms.prep", "Prepositions", "6–8", 6, 8),
    _t("fre.ms.qwords", "Question words", "6–8", 6, 8),
    _t("fre.ms.present", "Present tense review", "6–8", 6, 8),
    _t("fre.ms.pchave", "Passé composé with avoir", "6–8", 7, 8, "passe compose"),
    _t("fre.ms.pcetre", "Passé composé with être", "6–8", 8, 8),
    _t("fre.ms.imp", "Imparfait (intro)", "6–8", 8, 8, "imparfait"),
    _t("fre.ms.futur_p", "Futur proche", "6–8", 6, 8),
    _t("fre.ms.obj", "Object pronouns (intro)", "6–8", 8, 8),
    _t("fre.ms.comp", "Comparatives", "6–8", 7, 8),
    _t("fre.ms.read", "Reading short texts", "6–8", 6, 8),
    _t("fre.ms.para", "Writing a paragraph in French", "6–8", 7, 8),
    _t("fre.ms.dialogue", "Dialogue practice", "6–8", 6, 8),
    _t("fre.ms.liaison", "Pronunciation: liaison", "6–8", 6, 8),
    _t("fre.ms.nasal", "Pronunciation: nasal vowels", "6–8", 6, 8),
    _t("fre.ms.silent", "Silent letters", "6–8", 6, 8),
    # --- HS: writing / speaking ---
    _t("fre.hs.present", "Present tense mastery", "HS Fr", 9, 12),
    _t("fre.hs.pc_imp", "Passé composé versus imparfait", "HS Fr", 9, 12),
    _t("fre.hs.futur", "Futur simple", "HS Fr", 9, 12),
    _t("fre.hs.cond", "Le conditionnel", "HS Fr", 10, 12),
    _t("fre.hs.subj", "Le subjonctif (intro)", "HS Fr", 10, 12),
    _t("fre.hs.pqp", "Plus-que-parfait (intro)", "HS Fr", 11, 12),
    _t("fre.hs.pronom", "Pronominal verbs", "HS Fr", 9, 12),
    _t("fre.hs.cod", "Direct and indirect objects", "HS Fr", 9, 12),
    _t("fre.hs.yen", "Y and en", "HS Fr", 10, 12),
    _t("fre.hs.rel", "Relative pronouns", "HS Fr", 10, 12),
    _t("fre.hs.si", "Si clauses", "HS Fr", 10, 12),
    _t("fre.hs.tu_vous", "Tu versus vous", "HS Fr", 9, 12),
    _t("fre.hs.literary", "Literary tenses (intro)", "HS Fr", 12, 13),
    _t("fre.hs.authentic", "Reading authentic texts", "HS Fr", 10, 12),
    _t("fre.hs.essay", "Essay writing in French", "HS Fr", 10, 13),
    _t("fre.hs.oral", "Oral presentation in French", "HS Fr", 9, 12),
    _t("fre.hs.debate", "Giving an opinion in French", "HS Fr", 10, 12),
    _t("fre.hs.culture", "Culture and la francophonie", "HS Fr", 9, 13),
    _t("fre.hs.idiom", "Idioms", "HS Fr", 10, 12),
    _t("fre.hs.translate", "Translation pitfalls", "HS Fr", 11, 13),
    _t("fre.hs.register", "Register and politeness", "HS Fr", 10, 12),
    _t("fre.hs.listen", "Listening to native speech", "HS Fr", 9, 12),
    _t("fre.hs.creative", "Creative writing in French", "HS Fr", 10, 13),
    _t("fre.hs.exam", "Exam-style writing", "HS Fr", 11, 13),
]


CATALOGS: Dict[str, List[Dict[str, Any]]] = {
    "mathematics": MATH_TOPICS,
    "physics": PHYSICS_TOPICS,
    "chemistry": CHEMISTRY_TOPICS,
    "biology": BIOLOGY_TOPICS,
    "philosophy": PHILOSOPHY_TOPICS,
    "english": ENGLISH_TOPICS,
    "french": FRENCH_TOPICS,
}


def list_subjects() -> List[Dict[str, Any]]:
    out = []
    for sid in SUBJECTS:
        topics = CATALOGS[sid]
        walkable = any(t.get("walkable") for t in topics)
        out.append({
            "id": sid,
            "title": SUBJECT_TITLES[sid],
            "walkable": walkable,
            "topic_count": len([t for t in topics if t.get("walkable")]) if walkable else 0,
            "status": "ready" if walkable else "skeleton",
        })
    return out


def get_topics(subject: str) -> List[Dict[str, Any]]:
    return list(CATALOGS.get(_norm_subject(subject) or "", []))


def get_topic(subject: str, topic_id: str) -> Optional[Dict[str, Any]]:
    for t in get_topics(subject):
        if t["id"] == topic_id:
            return t
    return None


def topic_index(subject: str, topic_id: str) -> int:
    for i, t in enumerate(get_topics(subject)):
        if t["id"] == topic_id:
            return i
    return -1


def next_topic(subject: str, topic_id: str) -> Optional[Dict[str, Any]]:
    topics = [t for t in get_topics(subject) if t.get("walkable")]
    for i, t in enumerate(topics):
        if t["id"] == topic_id and i + 1 < len(topics):
            return topics[i + 1]
    return None


def first_topic(subject: str) -> Optional[Dict[str, Any]]:
    for t in get_topics(subject):
        if t.get("walkable"):
            return t
    return None


def _norm_subject(raw: Optional[str]) -> Optional[str]:
    if not raw:
        return None
    key = raw.strip().lower()
    if key in CATALOGS:
        return key
    for sid, aliases in SUBJECT_ALIASES.items():
        if key == sid or key in aliases:
            return sid
    return None


def match_topic(message: str, subject: Optional[str] = None) -> Optional[Dict[str, Any]]:
    text = (message or "").lower()
    subjects = [subject] if subject else list(CATALOGS)
    best = None
    best_len = 0
    for sid in subjects:
        if sid not in CATALOGS:
            continue
        for t in CATALOGS[sid]:
            needles = [t["title"].lower(), *(a.lower() for a in t.get("aliases") or [])]
            for n in needles:
                if n and n in text and len(n) > best_len:
                    best = {**t, "subject": sid}
                    best_len = len(n)
    return best


def parse_intent(message: str) -> Dict[str, Any]:
    text = (message or "").strip()
    lower = text.lower()
    from_scratch = any(p in lower for p in FROM_SCRATCH_PHRASES)
    wants_resume = (not from_scratch) and any(p in lower for p in RESUME_PHRASES)
    explicit_subject = None
    for sid, aliases in SUBJECT_ALIASES.items():
        if any(re.search(rf"\b{re.escape(a)}\b", lower) for a in aliases):
            explicit_subject = sid
            break
    subject = explicit_subject
    hit = match_topic(text, subject)
    if hit and not subject:
        subject = hit.get("subject")
    if not hit and (subject or "mathematics"):
        for hint, band in BAND_HINTS:
            if hint in lower:
                subj = subject or "mathematics"
                for t in get_topics(subj):
                    if t.get("walkable") and t.get("band") == band:
                        hit = {**t, "subject": subj}
                        subject = subj
                        break
                break
    # Bare topic-title hits stay free-ask (e.g. "How does Photosynthesis work?").
    # A named subject, from-scratch, resume/continue, or track phrase starts a track.
    wants = from_scratch or wants_resume or any(p in lower for p in TRACK_INTENT_PHRASES)
    if explicit_subject:
        wants = True
    return {
        "wants_track": bool(wants),
        "subject": subject,
        "explicit_subject": explicit_subject,
        "from_scratch": from_scratch,
        "resume": bool(wants_resume),
        "topic": hit,
        "message": text,
    }


def lesson_prompt(
    topic: Dict[str, Any],
    struggles: Optional[List[str]] = None,
    from_scratch: bool = False,
    subject: Optional[str] = None,
) -> str:
    struggle_txt = "; ".join(struggles or []) or "none recorded yet"
    sid = (subject or topic.get("subject") or "").lower()
    extras = {
        "mathematics": "Use GraphCard or FormulaCard when the math is visual.",
        "physics": "Use GraphCard or FormulaCard when the science is visual.",
        "chemistry": "Use FormulaCard for reactions and equations. Use GraphCard only for real data such as titration or rates.",
        "biology": "Use FormulaCard only if a real process equation helps. Do not invent unrelated graphs.",
        "philosophy": "Use TextBlock for ideas, examples, and questions. Do not invent GraphCard or fake science graphs.",
        "english": "Use PronunciationCard for alphabet, phonics, and speaking. Use TextBlock for reading and grammar. Do not invent graphs.",
        "french": "Use PronunciationCard for alphabet, accents, and speaking. Include French examples. Do not invent graphs.",
    }
    extra = extras.get(sid, "Use GraphCard or FormulaCard only when they truly help.")
    tid = (topic.get("id") or "")
    title = (topic.get("title") or "").lower()
    if tid == "math.k2.counting" or "counting to 20" in title:
        extra = (
            'Use a GraphCard with model_type "counting" and count: 20. '
            "The UI draws TWO COLUMNS: numeral on the left, that many dots on the right, "
            "one row per number from 1 to 20. "
            "Do NOT write wrapping inline text like 1:● 2:●● 3:●●● in formula, description, or body."
        )
    return (
        f"Teach this ONE K-12 topic as a Gandal Space A2UI lesson. "
        f"Topic: {topic['title']}. Band: {topic.get('band')}. "
        f"Grades {topic.get('grade_lo')}–{topic.get('grade_hi')}. "
        f"Student starting from scratch: {bool(from_scratch)}. "
        f"Known struggles: {struggle_txt}. "
        "Stay on this topic only — do not list the rest of the track. "
        f"Include a QuizCard. {extra}"
    )


def public_topic(topic: Dict[str, Any], subject: str, index: int, total: int) -> Dict[str, Any]:
    return {
        "id": topic["id"],
        "title": topic["title"],
        "band": topic.get("band"),
        "grade_lo": topic.get("grade_lo"),
        "grade_hi": topic.get("grade_hi"),
        "walkable": bool(topic.get("walkable")),
        "subject": subject,
        "subject_title": SUBJECT_TITLES.get(subject, subject),
        "index": index,
        "total": total,
        "lesson_prompt": lesson_prompt(topic, subject=subject),
    }


def _truthy(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return str(value or "").strip().lower() in ("1", "true", "yes")


def _as_list(value: Any) -> List[str]:
    if isinstance(value, list):
        return [str(x) for x in value if str(x).strip()]
    if not value:
        return []
    return [p.strip() for p in str(value).split(",") if p.strip()]


def _replace_section(body: str, heading: str, bullets: List[str]) -> str:
    block = f"## {heading}\n" + "\n".join(bullets) + "\n"
    pattern = rf"(## {re.escape(heading)}[^\n]*\n)(.*?)(?=\n## |\Z)"
    match = re.search(pattern, body or "", re.DOTALL)
    if match:
        return body.replace(match.group(0), block)
    return ((body or "").rstrip() + "\n\n" + block).strip() + "\n"


def _read_struggles(student_id: str, subject_title: str) -> List[str]:
    _meta, body = student_memory.load_or_create_subject_profile(student_id, subject_title)
    match = re.search(r"## Where They Struggle\n(.*?)(?=\n## |\Z)", body or "", re.DOTALL)
    if not match:
        return []
    out = []
    for line in match.group(1).splitlines():
        item = line.strip().lstrip("*-").strip()
        if item and "Initial application of" not in item:
            out.append(item)
    return out[:8]


def current_progress(student_id: str) -> Optional[Dict[str, Any]]:
    meta, _body = student_memory.load_or_create_session_state(student_id)
    subject = _norm_subject(meta.get("track_subject"))
    topic_id = meta.get("track_topic_id")
    if not subject or not topic_id:
        return None
    topic = get_topic(subject, str(topic_id))
    if not topic:
        return None
    walkable = [t for t in get_topics(subject) if t.get("walkable")]
    idx = topic_index(subject, topic["id"])
    completed = _as_list(meta.get("track_completed"))
    return {
        "student_id": student_id,
        "subject": subject,
        "from_scratch": _truthy(meta.get("track_from_scratch")),
        "completed_ids": completed,
        "completed_count": len(completed),
        "topic": public_topic(topic, subject, idx if idx >= 0 else 0, len(walkable)),
        "active": True,
    }


def start_track(student_id: str, subject: str, from_scratch: bool = False, topic_id: Optional[str] = None) -> Dict[str, Any]:
    sid = _norm_subject(subject)
    if not sid:
        return {"success": False, "error": "Unknown subject."}
    walkable = [t for t in get_topics(sid) if t.get("walkable")]
    if not walkable:
        title = SUBJECT_TITLES[sid]
        return {
            "success": False,
            "walkable": False,
            "subject": sid,
            "error": f"{title} is in the picker but not walkable yet.",
        }

    existing = current_progress(student_id) if not from_scratch and not topic_id else None
    if existing and existing.get("subject") == sid:
        topic = get_topic(sid, existing["topic"]["id"])
        completed = existing.get("completed_ids") or []
    else:
        topic = get_topic(sid, topic_id) if topic_id else None
        if not topic or not topic.get("walkable"):
            topic = first_topic(sid)
        completed = [] if from_scratch else _as_list(
            student_memory.load_or_create_session_state(student_id)[0].get("track_completed")
        )
    if not topic:
        return {"success": False, "error": "No walkable topics."}

    idx = topic_index(sid, topic["id"])
    struggles = _read_struggles(student_id, SUBJECT_TITLES[sid])
    prompt = lesson_prompt(topic, struggles=struggles, from_scratch=from_scratch, subject=sid)
    _write_session(
        student_id,
        sid,
        topic,
        completed,
        from_scratch=from_scratch,
        activity=f"Opened topic: {topic['title']}",
        next_action="Study the lesson, then take the quiz to advance.",
    )
    return {
        "success": True,
        "walkable": True,
        "subject": sid,
        "from_scratch": from_scratch,
        "completed_ids": completed,
        "completed_count": len(completed),
        "topic": {**public_topic(topic, sid, idx, len(walkable)), "lesson_prompt": prompt},
        "struggles": struggles,
    }


def apply_quiz(student_id: str, topic_id: str, correct: bool, question: str = "") -> Dict[str, Any]:
    progress = current_progress(student_id)
    if not progress:
        return {"success": False, "error": "No active K-12 track. Tell Gandho what you want to learn."}
    subject = progress["subject"]
    current = get_topic(subject, progress["topic"]["id"])
    if not current or current["id"] != topic_id:
        current = get_topic(subject, topic_id) or current
    if not current:
        return {"success": False, "error": "Unknown topic."}

    title = SUBJECT_TITLES[subject]
    meta, body = student_memory.load_or_create_subject_profile(student_id, title)
    meta["last_updated"] = __import__("datetime").datetime.utcnow().isoformat() + "Z"
    if correct:
        body = student_memory.merge_bullets(body, "Where They Excel", [current["title"]])
        completed = list(progress.get("completed_ids") or [])
        if current["id"] not in completed:
            completed.append(current["id"])
        nxt = next_topic(subject, current["id"])
        if nxt:
            _write_session(
                student_id, subject, nxt, completed, progress.get("from_scratch"),
                activity=f"Passed quiz on {current['title']}",
                next_action=f"Continue to {nxt['title']}",
            )
            walkable = [t for t in get_topics(subject) if t.get("walkable")]
            struggles = _read_struggles(student_id, title)
            student_memory.save_okf_file(student_id, f"subject_{title}.md", meta, body)
            return {
                "success": True,
                "correct": True,
                "advanced": True,
                "finished": False,
                "topic": {
                    **public_topic(nxt, subject, topic_index(subject, nxt["id"]), len(walkable)),
                    "lesson_prompt": lesson_prompt(nxt, struggles=struggles, subject=subject),
                },
            }
        _write_session(
            student_id, subject, current, completed, progress.get("from_scratch"),
            activity=f"Finished {title} track through {current['title']}",
            next_action="Track complete. Free-explore or pick another subject.",
        )
        student_memory.save_okf_file(student_id, f"subject_{title}.md", meta, body)
        return {"success": True, "correct": True, "advanced": False, "finished": True, "topic": progress["topic"]}

    note = current["title"]
    if question:
        note = f"{current['title']} (missed: {question[:80]})"
    body = student_memory.merge_bullets(body, "Where They Struggle", [note])
    student_memory.save_okf_file(student_id, f"subject_{title}.md", meta, body)
    _write_session(
        student_id, subject, current, progress.get("completed_ids") or [],
        progress.get("from_scratch"),
        activity=f"Missed quiz on {current['title']}",
        next_action="Retry the quiz, then advance.",
    )
    return {
        "success": True,
        "correct": False,
        "advanced": False,
        "finished": False,
        "topic": progress["topic"],
        "struggle": note,
    }


def exit_track(student_id: str) -> Dict[str, Any]:
    progress = current_progress(student_id)
    meta, body = student_memory.load_or_create_session_state(student_id)
    meta["track_active"] = "false"
    student_memory.save_okf_file(student_id, "session_state.md", meta, body)
    return {"success": True, "exited": True, "bookmark": progress}


def handle_intent(student_id: str, message: str) -> Dict[str, Any]:
    parsed = parse_intent(message)
    if not parsed["wants_track"]:
        return {"success": True, "matched": False, "intent": parsed}
    progress = current_progress(student_id)
    if parsed.get("resume") and not parsed["from_scratch"]:
        subject = parsed.get("explicit_subject") or (progress["subject"] if progress else None) or "mathematics"
        started = start_track(student_id, subject, from_scratch=False)
        return _intent_started(parsed, started, from_scratch=False)
    subject = parsed["subject"] or "mathematics"
    topic = parsed.get("topic")
    topic_id = topic["id"] if topic and topic.get("subject", subject) == subject else None
    if parsed["from_scratch"]:
        topic_id = None
    started = start_track(student_id, subject, from_scratch=parsed["from_scratch"], topic_id=topic_id)
    return _intent_started(parsed, started, from_scratch=parsed["from_scratch"])


def _intent_started(parsed: Dict[str, Any], started: Dict[str, Any], from_scratch: bool) -> Dict[str, Any]:
    if not started.get("success"):
        return {
            "success": False,
            "matched": True,
            "intent": parsed,
            "reply": started.get("error"),
            **started,
        }
    subject = started.get("subject") or parsed.get("subject") or "mathematics"
    topic_pub = started["topic"]
    if from_scratch:
        reply = (
            f"We will start {SUBJECT_TITLES.get(subject, subject)} from the beginning. "
            f"First topic only: {topic_pub['title']} ({topic_pub['band']}). "
            "The rest of the track stays hidden. Quiz, then we move on."
        )
    else:
        reply = (
            f"One topic at a time: {topic_pub['title']} ({topic_pub['band']}, "
            f"{topic_pub['index'] + 1} of {topic_pub['total']}). "
            "Quiz when you are ready and I will advance you."
        )
    return {
        "success": True,
        "matched": True,
        "intent": parsed,
        "reply": reply,
        **started,
    }


def _write_session(
    student_id: str,
    subject: str,
    topic: Dict[str, Any],
    completed: List[str],
    from_scratch: Any,
    activity: str,
    next_action: str,
) -> None:
    import datetime

    meta, body = student_memory.load_or_create_session_state(student_id)
    meta["status"] = "active"
    meta["last_session_time"] = datetime.datetime.utcnow().isoformat() + "Z"
    meta["subject"] = SUBJECT_TITLES[subject]
    meta["track_active"] = "true"
    meta["track_subject"] = subject
    meta["track_topic_id"] = topic["id"]
    meta["track_from_scratch"] = "true" if _truthy(from_scratch) else "false"
    meta["track_completed"] = list(completed)
    walkable = [t for t in get_topics(subject) if t.get("walkable")]
    idx = topic_index(subject, topic["id"])
    bullets = [
        f"* **Subject**: {SUBJECT_TITLES[subject]}",
        f"* **Current Topic**: {topic['title']}",
        f"* **Topic ID**: {topic['id']}",
        f"* **Position**: {idx + 1} of {len(walkable)}",
        f"* **Completed**: {len(completed)}",
        f"* **Last Activity**: {activity}",
        f"* **Next Best Action**: {next_action}",
    ]
    body = _replace_section(body, "K-12 Track", bullets)
    student_memory.save_okf_file(student_id, "session_state.md", meta, body)
